// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: common/proto/consensus.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- COMMON MESSAGES ---
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_common_proto_consensus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_consensus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_common_proto_consensus_proto_rawDescGZIP(), []int{0}
}

type LogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Term  int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Index int64                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// [LAB REQUIREMENT] "Message đặc biệt giả lập Block"
	// Raft sẽ lưu JSON string của Block vào field 'command' này
	Command       string `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_common_proto_consensus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_consensus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_common_proto_consensus_proto_rawDescGZIP(), []int{1}
}

func (x *LogEntry) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LogEntry) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type RequestVoteArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId   int32                  `protobuf:"varint,2,opt,name=candidateId,proto3" json:"candidateId,omitempty"` // Raft dùng int32 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteArgs) Reset() {
	*x = RequestVoteArgs{}
	mi := &file_common_proto_consensus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteArgs) ProtoMessage() {}

func (x *RequestVoteArgs) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_consensus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteArgs.ProtoReflect.Descriptor instead.
func (*RequestVoteArgs) Descriptor() ([]byte, []int) {
	return file_common_proto_consensus_proto_rawDescGZIP(), []int{2}
}

func (x *RequestVoteArgs) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteArgs) GetCandidateId() int32 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

type RequestVoteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteReply) Reset() {
	*x = RequestVoteReply{}
	mi := &file_common_proto_consensus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteReply) ProtoMessage() {}

func (x *RequestVoteReply) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_consensus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteReply.ProtoReflect.Descriptor instead.
func (*RequestVoteReply) Descriptor() ([]byte, []int) {
	return file_common_proto_consensus_proto_rawDescGZIP(), []int{3}
}

func (x *RequestVoteReply) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteReply) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type AppendEntriesArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      int32                  `protobuf:"varint,2,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	Entries       []*LogEntry            `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesArgs) Reset() {
	*x = AppendEntriesArgs{}
	mi := &file_common_proto_consensus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesArgs) ProtoMessage() {}

func (x *AppendEntriesArgs) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_consensus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesArgs.ProtoReflect.Descriptor instead.
func (*AppendEntriesArgs) Descriptor() ([]byte, []int) {
	return file_common_proto_consensus_proto_rawDescGZIP(), []int{4}
}

func (x *AppendEntriesArgs) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesArgs) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *AppendEntriesArgs) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type AppendEntriesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesReply) Reset() {
	*x = AppendEntriesReply{}
	mi := &file_common_proto_consensus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesReply) ProtoMessage() {}

func (x *AppendEntriesReply) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_consensus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesReply.ProtoReflect.Descriptor instead.
func (*AppendEntriesReply) Descriptor() ([]byte, []int) {
	return file_common_proto_consensus_proto_rawDescGZIP(), []int{5}
}

func (x *AppendEntriesReply) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Term          int64                  `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	mi := &file_common_proto_consensus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_consensus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_common_proto_consensus_proto_rawDescGZIP(), []int{6}
}

func (x *StatusReply) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StatusReply) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StatusReply) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type ProposeArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeArgs) Reset() {
	*x = ProposeArgs{}
	mi := &file_common_proto_consensus_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeArgs) ProtoMessage() {}

func (x *ProposeArgs) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_consensus_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeArgs.ProtoReflect.Descriptor instead.
func (*ProposeArgs) Descriptor() ([]byte, []int) {
	return file_common_proto_consensus_proto_rawDescGZIP(), []int{7}
}

func (x *ProposeArgs) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type ProposeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LeaderId      int32                  `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeReply) Reset() {
	*x = ProposeReply{}
	mi := &file_common_proto_consensus_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeReply) ProtoMessage() {}

func (x *ProposeReply) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_consensus_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeReply.ProtoReflect.Descriptor instead.
func (*ProposeReply) Descriptor() ([]byte, []int) {
	return file_common_proto_consensus_proto_rawDescGZIP(), []int{8}
}

func (x *ProposeReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProposeReply) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

type PartitionArgs struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IsolatedNodeIds []int32                `protobuf:"varint,1,rep,packed,name=isolatedNodeIds,proto3" json:"isolatedNodeIds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PartitionArgs) Reset() {
	*x = PartitionArgs{}
	mi := &file_common_proto_consensus_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionArgs) ProtoMessage() {}

func (x *PartitionArgs) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_consensus_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionArgs.ProtoReflect.Descriptor instead.
func (*PartitionArgs) Descriptor() ([]byte, []int) {
	return file_common_proto_consensus_proto_rawDescGZIP(), []int{9}
}

func (x *PartitionArgs) GetIsolatedNodeIds() []int32 {
	if x != nil {
		return x.IsolatedNodeIds
	}
	return nil
}

type PartitionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionReply) Reset() {
	*x = PartitionReply{}
	mi := &file_common_proto_consensus_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionReply) ProtoMessage() {}

func (x *PartitionReply) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_consensus_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionReply.ProtoReflect.Descriptor instead.
func (*PartitionReply) Descriptor() ([]byte, []int) {
	return file_common_proto_consensus_proto_rawDescGZIP(), []int{10}
}

func (x *PartitionReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PbftMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Header
	Type   string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                   // "PrePrepare", "Prepare", "Commit"
	NodeId string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // pBFT dùng string ID (VD: "node1")
	// Payload (View/Sequence)
	View     int64 `protobuf:"varint,3,opt,name=view,proto3" json:"view,omitempty"` // Thay cho Epoch (để rõ nghĩa pBFT)
	Sequence int64 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Block Info
	BlockHash     string `protobuf:"bytes,5,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	PrevBlockHash string `protobuf:"bytes,6,opt,name=prev_block_hash,json=prevBlockHash,proto3" json:"prev_block_hash,omitempty"`
	Data          string `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"` // Nội dung Block
	Timestamp     int64  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbftMessage) Reset() {
	*x = PbftMessage{}
	mi := &file_common_proto_consensus_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbftMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbftMessage) ProtoMessage() {}

func (x *PbftMessage) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_consensus_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbftMessage.ProtoReflect.Descriptor instead.
func (*PbftMessage) Descriptor() ([]byte, []int) {
	return file_common_proto_consensus_proto_rawDescGZIP(), []int{11}
}

func (x *PbftMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PbftMessage) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PbftMessage) GetView() int64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PbftMessage) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PbftMessage) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *PbftMessage) GetPrevBlockHash() string {
	if x != nil {
		return x.PrevBlockHash
	}
	return ""
}

func (x *PbftMessage) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *PbftMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PbftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbftResponse) Reset() {
	*x = PbftResponse{}
	mi := &file_common_proto_consensus_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbftResponse) ProtoMessage() {}

func (x *PbftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_consensus_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbftResponse.ProtoReflect.Descriptor instead.
func (*PbftResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_consensus_proto_rawDescGZIP(), []int{12}
}

func (x *PbftResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PbftResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_common_proto_consensus_proto protoreflect.FileDescriptor

const file_common_proto_consensus_proto_rawDesc = "" +
	"\n" +
	"\x1ccommon/proto/consensus.proto\x12\x06common\"\a\n" +
	"\x05Empty\"N\n" +
	"\bLogEntry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x03R\x05index\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\"G\n" +
	"\x0fRequestVoteArgs\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12 \n" +
	"\vcandidateId\x18\x02 \x01(\x05R\vcandidateId\"I\n" +
	"\x10RequestVoteReply\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12!\n" +
	"\fvote_granted\x18\x02 \x01(\bR\vvoteGranted\"o\n" +
	"\x11AppendEntriesArgs\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x1a\n" +
	"\bleaderId\x18\x02 \x01(\x05R\bleaderId\x12*\n" +
	"\aentries\x18\x03 \x03(\v2\x10.common.LogEntryR\aentries\"B\n" +
	"\x12AppendEntriesReply\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"G\n" +
	"\vStatusReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x03R\x04term\"'\n" +
	"\vProposeArgs\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"E\n" +
	"\fProposeReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x05R\bleaderId\"9\n" +
	"\rPartitionArgs\x12(\n" +
	"\x0fisolatedNodeIds\x18\x01 \x03(\x05R\x0fisolatedNodeIds\"*\n" +
	"\x0ePartitionReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xe3\x01\n" +
	"\vPbftMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04view\x18\x03 \x01(\x03R\x04view\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x03R\bsequence\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x05 \x01(\tR\tblockHash\x12&\n" +
	"\x0fprev_block_hash\x18\x06 \x01(\tR\rprevBlockHash\x12\x12\n" +
	"\x04data\x18\a \x01(\tR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\"B\n" +
	"\fPbftResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb6\x03\n" +
	"\x10ConsensusService\x12@\n" +
	"\vRequestVote\x12\x17.common.RequestVoteArgs\x1a\x18.common.RequestVoteReply\x12F\n" +
	"\rAppendEntries\x12\x19.common.AppendEntriesArgs\x1a\x1a.common.AppendEntriesReply\x12D\n" +
	"\x13SetNetworkPartition\x12\x15.common.PartitionArgs\x1a\x16.common.PartitionReply\x12/\n" +
	"\tGetStatus\x12\r.common.Empty\x1a\x13.common.StatusReply\x124\n" +
	"\aPropose\x12\x13.common.ProposeArgs\x1a\x14.common.ProposeReply\x12+\n" +
	"\vForceLeader\x12\r.common.Empty\x1a\r.common.Empty\x12>\n" +
	"\x11HandlePbftMessage\x12\x13.common.PbftMessage\x1a\x14.common.PbftResponseB\x0eZ\fcommon/protob\x06proto3"

var (
	file_common_proto_consensus_proto_rawDescOnce sync.Once
	file_common_proto_consensus_proto_rawDescData []byte
)

func file_common_proto_consensus_proto_rawDescGZIP() []byte {
	file_common_proto_consensus_proto_rawDescOnce.Do(func() {
		file_common_proto_consensus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_consensus_proto_rawDesc), len(file_common_proto_consensus_proto_rawDesc)))
	})
	return file_common_proto_consensus_proto_rawDescData
}

var file_common_proto_consensus_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_common_proto_consensus_proto_goTypes = []any{
	(*Empty)(nil),              // 0: common.Empty
	(*LogEntry)(nil),           // 1: common.LogEntry
	(*RequestVoteArgs)(nil),    // 2: common.RequestVoteArgs
	(*RequestVoteReply)(nil),   // 3: common.RequestVoteReply
	(*AppendEntriesArgs)(nil),  // 4: common.AppendEntriesArgs
	(*AppendEntriesReply)(nil), // 5: common.AppendEntriesReply
	(*StatusReply)(nil),        // 6: common.StatusReply
	(*ProposeArgs)(nil),        // 7: common.ProposeArgs
	(*ProposeReply)(nil),       // 8: common.ProposeReply
	(*PartitionArgs)(nil),      // 9: common.PartitionArgs
	(*PartitionReply)(nil),     // 10: common.PartitionReply
	(*PbftMessage)(nil),        // 11: common.PbftMessage
	(*PbftResponse)(nil),       // 12: common.PbftResponse
}
var file_common_proto_consensus_proto_depIdxs = []int32{
	1,  // 0: common.AppendEntriesArgs.entries:type_name -> common.LogEntry
	2,  // 1: common.ConsensusService.RequestVote:input_type -> common.RequestVoteArgs
	4,  // 2: common.ConsensusService.AppendEntries:input_type -> common.AppendEntriesArgs
	9,  // 3: common.ConsensusService.SetNetworkPartition:input_type -> common.PartitionArgs
	0,  // 4: common.ConsensusService.GetStatus:input_type -> common.Empty
	7,  // 5: common.ConsensusService.Propose:input_type -> common.ProposeArgs
	0,  // 6: common.ConsensusService.ForceLeader:input_type -> common.Empty
	11, // 7: common.ConsensusService.HandlePbftMessage:input_type -> common.PbftMessage
	3,  // 8: common.ConsensusService.RequestVote:output_type -> common.RequestVoteReply
	5,  // 9: common.ConsensusService.AppendEntries:output_type -> common.AppendEntriesReply
	10, // 10: common.ConsensusService.SetNetworkPartition:output_type -> common.PartitionReply
	6,  // 11: common.ConsensusService.GetStatus:output_type -> common.StatusReply
	8,  // 12: common.ConsensusService.Propose:output_type -> common.ProposeReply
	0,  // 13: common.ConsensusService.ForceLeader:output_type -> common.Empty
	12, // 14: common.ConsensusService.HandlePbftMessage:output_type -> common.PbftResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_common_proto_consensus_proto_init() }
func file_common_proto_consensus_proto_init() {
	if File_common_proto_consensus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_consensus_proto_rawDesc), len(file_common_proto_consensus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_consensus_proto_goTypes,
		DependencyIndexes: file_common_proto_consensus_proto_depIdxs,
		MessageInfos:      file_common_proto_consensus_proto_msgTypes,
	}.Build()
	File_common_proto_consensus_proto = out.File
	file_common_proto_consensus_proto_goTypes = nil
	file_common_proto_consensus_proto_depIdxs = nil
}
