# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"\x07\n\x05\x45mpty\"8\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\r\n\x05index\x18\x02 \x01(\x03\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\t\"4\n\x0fRequestVoteArgs\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x05\"6\n\x10RequestVoteReply\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"T\n\x11\x41ppendEntriesArgs\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x10\n\x08leaderId\x18\x02 \x01(\x05\x12\x1f\n\x07\x65ntries\x18\x03 \x03(\x0b\x32\x0e.raft.LogEntry\"3\n\x12\x41ppendEntriesReply\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x0f\n\x07success\x18\x02 \x01(\x08\"6\n\x0bStatusReply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05state\x18\x02 \x01(\t\x12\x0c\n\x04term\x18\x03 \x01(\x03\"\x1e\n\x0bProposeArgs\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"2\n\x0cProposeReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tleader_id\x18\x02 \x01(\x05\"(\n\rPartitionArgs\x12\x17\n\x0fisolatedNodeIds\x18\x01 \x03(\x05\"!\n\x0ePartitionReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xb0\x02\n\x0bRaftService\x12<\n\x0bRequestVote\x12\x15.raft.RequestVoteArgs\x1a\x16.raft.RequestVoteReply\x12\x42\n\rAppendEntries\x12\x17.raft.AppendEntriesArgs\x1a\x18.raft.AppendEntriesReply\x12@\n\x13SetNetworkPartition\x12\x13.raft.PartitionArgs\x1a\x14.raft.PartitionReply\x12+\n\tGetStatus\x12\x0b.raft.Empty\x1a\x11.raft.StatusReply\x12\x30\n\x07Propose\x12\x11.raft.ProposeArgs\x1a\x12.raft.ProposeReplyB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_LOGENTRY']._serialized_start=29
  _globals['_LOGENTRY']._serialized_end=85
  _globals['_REQUESTVOTEARGS']._serialized_start=87
  _globals['_REQUESTVOTEARGS']._serialized_end=139
  _globals['_REQUESTVOTEREPLY']._serialized_start=141
  _globals['_REQUESTVOTEREPLY']._serialized_end=195
  _globals['_APPENDENTRIESARGS']._serialized_start=197
  _globals['_APPENDENTRIESARGS']._serialized_end=281
  _globals['_APPENDENTRIESREPLY']._serialized_start=283
  _globals['_APPENDENTRIESREPLY']._serialized_end=334
  _globals['_STATUSREPLY']._serialized_start=336
  _globals['_STATUSREPLY']._serialized_end=390
  _globals['_PROPOSEARGS']._serialized_start=392
  _globals['_PROPOSEARGS']._serialized_end=422
  _globals['_PROPOSEREPLY']._serialized_start=424
  _globals['_PROPOSEREPLY']._serialized_end=474
  _globals['_PARTITIONARGS']._serialized_start=476
  _globals['_PARTITIONARGS']._serialized_end=516
  _globals['_PARTITIONREPLY']._serialized_start=518
  _globals['_PARTITIONREPLY']._serialized_end=551
  _globals['_RAFTSERVICE']._serialized_start=554
  _globals['_RAFTSERVICE']._serialized_end=858
# @@protoc_insertion_point(module_scope)
