// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/pbft.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBFTMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                            // "PrePrepare", "Prepare", "Commit"
	NodeId         string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                          // ID người gửi (Node ID)
	View           int64                  `protobuf:"varint,3,opt,name=view,proto3" json:"view,omitempty"`                                           // View hiện tại (Thay cho ViewID)
	SequenceNumber int64                  `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"` // Sequence (Thay cho SequenceID)
	BlockHash      string                 `protobuf:"bytes,5,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`                 // Hash của block hiện tại
	PrevBlockHash  string                 `protobuf:"bytes,6,opt,name=prev_block_hash,json=prevBlockHash,proto3" json:"prev_block_hash,omitempty"`   // [QUAN TRỌNG] Để nối chuỗi Blockchain
	Data           string                 `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`                                            // Dữ liệu (chỉ có trong PrePrepare)
	Timestamp      int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                 // Thời gian tạo
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PBFTMessage) Reset() {
	*x = PBFTMessage{}
	mi := &file_proto_pbft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBFTMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBFTMessage) ProtoMessage() {}

func (x *PBFTMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBFTMessage.ProtoReflect.Descriptor instead.
func (*PBFTMessage) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{0}
}

func (x *PBFTMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PBFTMessage) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PBFTMessage) GetView() int64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PBFTMessage) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *PBFTMessage) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *PBFTMessage) GetPrevBlockHash() string {
	if x != nil {
		return x.PrevBlockHash
	}
	return ""
}

func (x *PBFTMessage) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *PBFTMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PBFTResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBFTResponse) Reset() {
	*x = PBFTResponse{}
	mi := &file_proto_pbft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBFTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBFTResponse) ProtoMessage() {}

func (x *PBFTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBFTResponse.ProtoReflect.Descriptor instead.
func (*PBFTResponse) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{1}
}

func (x *PBFTResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PBFTResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_pbft_proto protoreflect.FileDescriptor

const file_proto_pbft_proto_rawDesc = "" +
	"\n" +
	"\x10proto/pbft.proto\x12\x04pbft\"\xf0\x01\n" +
	"\vPBFTMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04view\x18\x03 \x01(\x03R\x04view\x12'\n" +
	"\x0fsequence_number\x18\x04 \x01(\x03R\x0esequenceNumber\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x05 \x01(\tR\tblockHash\x12&\n" +
	"\x0fprev_block_hash\x18\x06 \x01(\tR\rprevBlockHash\x12\x12\n" +
	"\x04data\x18\a \x01(\tR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\"B\n" +
	"\fPBFTResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2J\n" +
	"\x10ConsensusService\x126\n" +
	"\rHandleMessage\x12\x11.pbft.PBFTMessage\x1a\x12.pbft.PBFTResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_pbft_proto_rawDescOnce sync.Once
	file_proto_pbft_proto_rawDescData []byte
)

func file_proto_pbft_proto_rawDescGZIP() []byte {
	file_proto_pbft_proto_rawDescOnce.Do(func() {
		file_proto_pbft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pbft_proto_rawDesc), len(file_proto_pbft_proto_rawDesc)))
	})
	return file_proto_pbft_proto_rawDescData
}

var file_proto_pbft_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_pbft_proto_goTypes = []any{
	(*PBFTMessage)(nil),  // 0: pbft.PBFTMessage
	(*PBFTResponse)(nil), // 1: pbft.PBFTResponse
}
var file_proto_pbft_proto_depIdxs = []int32{
	0, // 0: pbft.ConsensusService.HandleMessage:input_type -> pbft.PBFTMessage
	1, // 1: pbft.ConsensusService.HandleMessage:output_type -> pbft.PBFTResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_pbft_proto_init() }
func file_proto_pbft_proto_init() {
	if File_proto_pbft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pbft_proto_rawDesc), len(file_proto_pbft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pbft_proto_goTypes,
		DependencyIndexes: file_proto_pbft_proto_depIdxs,
		MessageInfos:      file_proto_pbft_proto_msgTypes,
	}.Build()
	File_proto_pbft_proto = out.File
	file_proto_pbft_proto_goTypes = nil
	file_proto_pbft_proto_depIdxs = nil
}
